export const campaigns = {
    campaignList: [
        {
            id: 1,
            title: 'Seçili Ürünler',
            description: 'Aynı Gün Teslim!',
            color: '#eb6b44',
            imageList: [],
            isActive: true,
            order: 1
        },
        {
            id: 2,
            title: 'Çiçek & Hediye',
            description: 'Çok Satanlar!',
            color: '#e27475',
            imageList: [],
            isActive: true,
            order: 2,
        },
        {
            id: 3,
            title: 'Doğum Günü Hediyeleri',
            description: 'Süper Fırsatlar!',
            color: '#66bbe0',
            imageList: [],
            isActive: true,
            order: 3,
        },
        {
            id: 4,
            title: 'En Özel Hediyeler',
            description: 'Aradığınız Ürünler!',
            color: '#7894e4',
            imageList: [],
            isActive: true,
            order: 4,
        },
        {
            id: 5,
            title: 'Tasarım Çiçekler',
            description: 'Süper Fırsatlar!',
            color: '#e27c65252475',
            imageList: [],
            isActive: true,
            order: 5,
        },
        {
            id: 6,
            title: 'Hediye Setleri',
            description: 'Avantajlı Fırsatlar!',
            color: '#f38760',
            imageList: [],
            isActive: true,
            order: 6,
        },
        {
            id: 7,
            title: 'Çiçek & Hediye',
            description: 'Çok Satanlar!',
            color: '#e27475',
            imageList: [],
            isActive: false,
            order: 7,
        },
        {
            id: 8,
            title: 'Çiçek & Hediye',
            description: 'Çok Satanlar!',
            color: '#e27475',
            imageList: [],
            isActive: false,
            order: 8,
        },
        {
            id: 9,
            title: 'Çiçek & Hediye',
            description: 'Çok Satanlar!',
            color: '#e27475',
            imageList: [],
            isActive: false,
            order: 9,
        }
    ]
};